config:
  dataset: 'missing'
  max_epochs: 5000
  batch_size: 10000
  min_delta: 0.000008
  patience: 50
  emb_dim: 4
  h_hidden_dim: 32
  latent_dim: 64
  hidden_layer_dim: 32
  mirt_dim: 3
  lr: .005

